### ISSUE TITLE
Check the channel spacing for 2.4GHz. 

### ISSUE THREAD

**Issue by changtengfei** [openwsn-berkeley/range_test#8]
For the channel spacing for 2.4GHz O-QPSK, it should be 3MHz, but need to be checked.

**Comment by twatteyne** [comment]
The spacing is 5MHz, the width is 2MHz

**Comment by changtengfei** [comment]
Thank you for clarifying. Then this line code should be upated: https://github.com/openwsn-berkeley/range_test/blob/experiment2dot4ghz/raspberry/experiment_settings.py#L15 with 5000 channel spacing.
